<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<CPackFileMetaData>
  <MapDataGroups/>
  <HDTxdBindingArray/>
  <imapDependencies/>
  <imapDependencies_2>
    <Item>
      <imapName>predio</imapName>
      <manifestFlags/>
      <itypDepArray>
      </itypDepArray>
    </Item>
    <Item>
      <imapName>dt1_rd1_strm_1</imapName>
      <manifestFlags/>
      <itypDepArray>
        <Item>v_industrial</Item>
        <Item>v_bins</Item>
        <Item>v_rooftop</Item>
        <Item>v_utility</Item>
        <Item>downtown_01_metadata_002_strm</Item>
        <Item>v_signs</Item>
        <Item>v_traffic_lights</Item>
        <Item>v_seating_tables</Item>
        <Item>v_rubbish</Item>
        <Item>v_construction</Item>
        <Item>v_storage</Item>
      </itypDepArray>
    </Item>
    <Item>
      <imapName>hei_dt1_rd1_strm_1</imapName>
      <manifestFlags/>
      <itypDepArray>
        <Item>v_industrial</Item>
        <Item>v_bins</Item>
        <Item>v_rooftop</Item>
        <Item>v_utility</Item>
        <Item>downtown_01_metadata_002_strm</Item>
        <Item>v_signs</Item>
        <Item>v_traffic_lights</Item>
        <Item>v_seating_tables</Item>
        <Item>v_rubbish</Item>
        <Item>v_construction</Item>
        <Item>v_storage</Item>
      </itypDepArray>
    </Item>
    <Item>
      <imapName>dt1_rd1_long_0</imapName>
      <manifestFlags/>
      <itypDepArray>
        <Item>v_palm</Item>
        <Item>v_bush</Item>
        <Item>v_rooftop</Item>
        <Item>v_signs</Item>
        <Item>v_fanpalm</Item>
        <Item>downtown_01_metadata_002_strm</Item>
        <Item>v_construction</Item>
        <Item>v_storage</Item>
      </itypDepArray>
    </Item>
    <Item>
      <imapName>hei_dt1_rd1_long_0</imapName>
      <manifestFlags/>
      <itypDepArray>
        <Item>v_palm</Item>
        <Item>v_bush</Item>
        <Item>v_rooftop</Item>
        <Item>v_signs</Item>
        <Item>v_fanpalm</Item>
        <Item>downtown_01_metadata_002_strm</Item>
        <Item>v_construction</Item>
        <Item>v_storage</Item>
      </itypDepArray>
    </Item>
    <Item>
      <imapName>dt1_12_strm_0</imapName>
      <manifestFlags/>
      <itypDepArray>
        <Item>downtown_01_metadata_008_strm</Item>
        <Item>v_utility</Item>
        <Item>v_potted</Item>
        <Item>v_traffic_lights</Item>
        <Item>v_rubbish</Item>
        <Item>v_bins</Item>
        <Item>v_seating_tables</Item>
        <Item>v_construction</Item>
        <Item>v_rooftop</Item>
      </itypDepArray>
    </Item>
    <Item>
      <imapName>hei_dt1_12_strm_0</imapName>
      <manifestFlags/>
      <itypDepArray>
        <Item>downtown_01_metadata_008_strm</Item>
        <Item>v_utility</Item>
        <Item>v_potted</Item>
        <Item>v_traffic_lights</Item>
        <Item>v_rubbish</Item>
        <Item>v_bins</Item>
        <Item>v_seating_tables</Item>
        <Item>v_construction</Item>
        <Item>v_rooftop</Item>
      </itypDepArray>
    </Item>
  </imapDependencies_2>
  <itypDependencies_2/>
  <Interiors/>
</CPackFileMetaData>

